return {
    { Name = "Carrot", Harvest = "Single", Cost = 10, Rarity = "Common" },
    { Name = "Strawberry", Harvest = "Multiple", Cost = 50, Rarity = "Common" },
    { Name = "Blueberry", Harvest = "Multiple", Cost = 400, Rarity = "Uncommon" },
    { Name = "Orange Tulip", Harvest = "Single", Cost = 600, Rarity = "Uncommon" },
    { Name = "Tomato", Harvest = "Multiple", Cost = 800, Rarity = "Rare" },
    { Name = "Corn", Harvest = "Multiple", Cost = 1300, Rarity = "Rare" },
    { Name = "Daffodil", Harvest = "Single", Cost = 1000, Rarity = "Rare" },
    { Name = "Watermelon", Harvest = "Single", Cost = 2500, Rarity = "Legendary" },
    { Name = "Pumpkin", Harvest = "Single", Cost = 3000, Rarity = "Legendary" },
    { Name = "Apple", Harvest = "Multiple", Cost = 3250, Rarity = "Legendary" },
    { Name = "Bamboo", Harvest = "Single", Cost = 4000, Rarity = "Legendary" },
    { Name = "Coconut", Harvest = "Multiple", Cost = 6000, Rarity = "Mythical" },
    { Name = "Cactus", Harvest = "Multiple", Cost = 15000, Rarity = "Mythical" },
    { Name = "Dragon Fruit", Harvest = "Multiple", Cost = 50000, Rarity = "Mythical" },
    { Name = "Mango", Harvest = "Multiple", Cost = 100000, Rarity = "Mythical" },
    { Name = "Grape", Harvest = "Multiple", Cost = 850000, Rarity = "Divine" },
    { Name = "Mushroom", Harvest = "Single", Cost = 150000, Rarity = "Divine" },
    { Name = "Pepper", Harvest = "Multiple", Cost = 1000000, Rarity = "Divine" },
    { Name = "Beanstalk", Harvest = "Multiple", Cost = 10000000, Rarity = "Prismatic" },
    { Name = "Ember Lily", Harvest = "Multiple", Cost = 15000000, Rarity = "Prismatic" },
    { Name = "Sugar Apple", Harvest = "Multiple", Cost = 25000000, Rarity = "Prismatic" },
    { Name = "Burning Bud", Harvest = "Multiple", Cost = 50000000, Rarity = "Prismatic" },
    { Name = "Giant Pinecone", Harvest = "Multiple", Cost = 55000000, Rarity = "Prismatic" },
    { Name = "Elder Strawberry", Harvest = "Multiple", Cost = 70000000, Rarity = "Prismatic" },
    { Name = "Romanesco", Harvest = "Multiple", Cost = 88000000, Rarity = "Prismatic" }
}
